/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TinderImport } from './routes/tinder'
import { Route as RatingImport } from './routes/rating'
import { Route as PaginationImport } from './routes/pagination'
import { Route as InfscrollImport } from './routes/infscroll'
import { Route as ClickerImport } from './routes/clicker'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TinderRoute = TinderImport.update({
  path: '/tinder',
  getParentRoute: () => rootRoute,
} as any)

const RatingRoute = RatingImport.update({
  path: '/rating',
  getParentRoute: () => rootRoute,
} as any)

const PaginationRoute = PaginationImport.update({
  path: '/pagination',
  getParentRoute: () => rootRoute,
} as any)

const InfscrollRoute = InfscrollImport.update({
  path: '/infscroll',
  getParentRoute: () => rootRoute,
} as any)

const ClickerRoute = ClickerImport.update({
  path: '/clicker',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clicker': {
      id: '/clicker'
      path: '/clicker'
      fullPath: '/clicker'
      preLoaderRoute: typeof ClickerImport
      parentRoute: typeof rootRoute
    }
    '/infscroll': {
      id: '/infscroll'
      path: '/infscroll'
      fullPath: '/infscroll'
      preLoaderRoute: typeof InfscrollImport
      parentRoute: typeof rootRoute
    }
    '/pagination': {
      id: '/pagination'
      path: '/pagination'
      fullPath: '/pagination'
      preLoaderRoute: typeof PaginationImport
      parentRoute: typeof rootRoute
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingImport
      parentRoute: typeof rootRoute
    }
    '/tinder': {
      id: '/tinder'
      path: '/tinder'
      fullPath: '/tinder'
      preLoaderRoute: typeof TinderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clicker': typeof ClickerRoute
  '/infscroll': typeof InfscrollRoute
  '/pagination': typeof PaginationRoute
  '/rating': typeof RatingRoute
  '/tinder': typeof TinderRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clicker': typeof ClickerRoute
  '/infscroll': typeof InfscrollRoute
  '/pagination': typeof PaginationRoute
  '/rating': typeof RatingRoute
  '/tinder': typeof TinderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/clicker': typeof ClickerRoute
  '/infscroll': typeof InfscrollRoute
  '/pagination': typeof PaginationRoute
  '/rating': typeof RatingRoute
  '/tinder': typeof TinderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clicker'
    | '/infscroll'
    | '/pagination'
    | '/rating'
    | '/tinder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clicker' | '/infscroll' | '/pagination' | '/rating' | '/tinder'
  id:
    | '__root__'
    | '/'
    | '/clicker'
    | '/infscroll'
    | '/pagination'
    | '/rating'
    | '/tinder'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClickerRoute: typeof ClickerRoute
  InfscrollRoute: typeof InfscrollRoute
  PaginationRoute: typeof PaginationRoute
  RatingRoute: typeof RatingRoute
  TinderRoute: typeof TinderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClickerRoute: ClickerRoute,
  InfscrollRoute: InfscrollRoute,
  PaginationRoute: PaginationRoute,
  RatingRoute: RatingRoute,
  TinderRoute: TinderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clicker",
        "/infscroll",
        "/pagination",
        "/rating",
        "/tinder"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clicker": {
      "filePath": "clicker.tsx"
    },
    "/infscroll": {
      "filePath": "infscroll.tsx"
    },
    "/pagination": {
      "filePath": "pagination.tsx"
    },
    "/rating": {
      "filePath": "rating.tsx"
    },
    "/tinder": {
      "filePath": "tinder.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
