/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TinderImport } from './routes/tinder'
import { Route as PaginationImport } from './routes/pagination'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TinderRoute = TinderImport.update({
  path: '/tinder',
  getParentRoute: () => rootRoute,
} as any)

const PaginationRoute = PaginationImport.update({
  path: '/pagination',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pagination': {
      id: '/pagination'
      path: '/pagination'
      fullPath: '/pagination'
      preLoaderRoute: typeof PaginationImport
      parentRoute: typeof rootRoute
    }
    '/tinder': {
      id: '/tinder'
      path: '/tinder'
      fullPath: '/tinder'
      preLoaderRoute: typeof TinderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagination': typeof PaginationRoute
  '/tinder': typeof TinderRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagination': typeof PaginationRoute
  '/tinder': typeof TinderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pagination': typeof PaginationRoute
  '/tinder': typeof TinderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagination' | '/tinder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagination' | '/tinder'
  id: '__root__' | '/' | '/pagination' | '/tinder'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaginationRoute: typeof PaginationRoute
  TinderRoute: typeof TinderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaginationRoute: PaginationRoute,
  TinderRoute: TinderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pagination",
        "/tinder"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pagination": {
      "filePath": "pagination.tsx"
    },
    "/tinder": {
      "filePath": "tinder.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
